version: '3.3'
services:
  redis:
    image: redis:latest
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.4'
          memory: '650M'
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
  service-registry:
    ports:
      - '8761:8761'
    container_name: service-registry
    restart: always
    image: 'service-registry:latest'

  gateway:
    ports:
      - '8080:8080'
    container_name: gateway
    environment:
      - EUREKA_URL=http://localhost:8761/eureka/
    restart: always
    image: 'gateway:latest'

  external-service:
    ports:
      - '8083:8083'
    container_name: external-service
    environment:
      - EUREKA_URL=http://localhost:8761/eureka/
    restart: always
    image: 'external-service:latest'

  api2-service:
    ports:
      - '8082:8082'
    container_name: api2-service
    environment:
      - EUREKA_URL=http://localhost:8761/eureka/
      - DATABASE_URL=jdbc:mysql://localhost:3306/api2
      - DATABASE_USER=root
      - DATABASE_PASS=YourPassword1!
    restart: always
    image: 'api2-service:latest'

  main-app:
    ports:
      - '8081:8081'
    container_name: main-app
    environment:
      - EUREKA_URL=http://localhost:8761/eureka/
      - REDIS_DB=localhost
      - REDIS_PORT=6379
    restart: always
    image: 'main-app:latest'